// static metadata 예제
// 참고 링크
// https://nextjs.org/docs/app/building-your-application/optimizing/metadata


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// 기존 메타 데이터 
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// view pagesource 를 보고 확인가능 (추가 해봄)
export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: `%s | Create Next App`
  },
  openGraph: {
    description: "Generated by create next app",
    images: ['']
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
